### PR TITLE
[fixed] use window.HTMLElement instead of HTMLElement so we can use with jsdom

### PR DESCRIPTION
**Pull request by ngduc**
Reference:
https://github.com/jquense/teaspoon/issues/22

Thanks.

### CODE REVIEW

**Comment by jquense** [comment]
thank you!

**Comment by smazurov** [comment]
Did you forget to also change it [here](https://github.com/jquense/teaspoon/blob/75a3b84ef02a84af7b30c40b2bc2fb0cce3d713e/src/utils.js#L182)?

**Comment by ngduc** [comment]
@smazurov I don't have issue with that line so far.
If you encounter an error with that, feel free to do a PR.

**Comment by smazurov** [comment]
I already did, and its been merged :)

**Pull request merged**
