### PR TITLE
Add a node() convenience method

### PR DESCRIPTION
**Pull request by dchambers**
This allows tests using `shallowRender()` to more easily access the rendered output.

### CODE REVIEW

**Comment by dchambers** [comment]
Hi @jquense, I just re-read your comment in #3 and noticed that you'd actually provided a neater solutions than what I originally implemented, so I've updated the pull-request to match.

**Comment by jquense** [comment]
looks good, I like the error, the only thing I'm not excited about is the name...

`node` doesn't really work since it's not necessarily returning some kind of node, perhaps something more descriptive of what its doing like `unwrap` is better?

**Comment by dchambers** [comment]
Agreed, `unwrap()` does seem more descriptive than `node()`. Here ya go...

**Comment by jquense** [comment]
:+1:

**Pull request merged**
