### PR TITLE
Use 'prepublish' script to ensure code is transpiled

### PR DESCRIPTION
**Pull request by dchambers**

### CODE REVIEW

**Comment by jquense** [comment]
hey, can you talk me through why this change? as it is it breaks my release workflow, the `release` script depends on a `build` script

**Comment by dchambers** [comment]
Ah, that's the script you're meant to use to create any target files.

`prepublish` is a special script since it not only gets run before `publish` (like all `pre<target>` scripts do) but it also gets run post-install. This means that it will definitely be run before you publish to NPM, **and** on the user's machine as they install.

You can run it manually as `npm run prepublish`, or if you still want a `build` command you can add this to your `package.json`:

```
"build": "npm run prepublish",
```

BTW, I only needed this because I'm converting another project I've been working on to use my fork of teaspoon from GitHub so that I can better answer your queries in my earlier pull-request :-).

**Comment by dchambers** [comment]
One weird thing I've noticed is that the `index.js` in the target `lib` directory becomes:

```
module['export'] = require('./element');
```

where I have to manually change `'export'` to `'exports'` to make it work. Not sure why that would be the case, but for the time being that would be a good reason not to accept this pull-request as it will break the library.

**Comment by dchambers** [comment]
Apologies for all the noise, but this does now appear to be working for me.

**Comment by jquense** [comment]
I can see why you'd want this but the problem is this change breaks my release to npm workflow completely. we really need the build script to remain untouched. 

tbh I am not super inclined to make this change since it makes the exception case (installing from github) work easier at the expense of the 95% case of installing from npm. why not just run `npm run build` after you install? or better yet why not just install from npm?

**Comment by jquense** [comment]
Sorry also the reason the lib index file doesn't work is because without running the release script it isn't properly copied from the src dir. :) 

thanks again for your interest and involvement here

**Comment by dchambers** [comment]
> I can see why you'd want this but the problem is this change breaks my release to npm workflow completely. we really need the build script to remain untouched.

Fair enough, it's your build system. What if I reverted `build` but then defined `prepublish as follows`:

```
  "prepublish": "npm run build",
```

> tbh I am not super inclined to make this change since it makes the exception case (installing from github) work easier at the expense of the 95% case of installing from npm. why not just run npm run build after you install? or better yet why not just install from npm?

Well, it's also about standardization, and allowing other people to easily make changes to your repo. You can normally do everything you want to a repo using `npm install`, `npm test` and `npm publish` alone.

It's also worth bearing in mind that most repos don't check their derived files into source control, at which point `npm install` becomes even more important, since you know that if you run that after a `git clone` you should be able to run `npm test` without problems. And of course, that's also what Travis does (`git clone; npm install; npm test`) for Node.js projects by default.

**Comment by dchambers** [comment]
> Sorry also the reason the lib index file doesn't work is because without running the release script it isn't properly copied from the src dir. :)

Okay, thanks for the heads up. Of course, this is more proof why doing this kind of stuff in `npm prepublish` makes things easier by reducing friction.

**Comment by jquense** [comment]
>Well, it's also about standardization, and allowing other people to easily make changes to your repo. You can normally do everything you want to a repo using npm install, npm test and npm publish alone.

I am going to have to disagree with you on this one, `build` is an extremely common script name for this sort of thing, and since I am the only one with permission to publish the module anyway I don't see how its use is more "standard" in terms of codebase approachability. 

I also know that many repos don't check in the compiled files, I do b/c sometimes I do install from github and instead of having a post install hook id rather just have the built files.

right now the build process is in inline with most other personal and organization projects I work on, so I think I prefer to just leave it as is, thanks.

**Pull request closed without merging**
